# Generated by Django 5.1.6 on 2025-02-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('astronomia', 'Astronomia'), ('ciencias', 'Ciências'), ('biologia', 'Biologia')], max_length=50)),
                ('imagem', models.ImageField(upload_to='cartas/')),
                ('modelo_3d', models.FileField(upload_to='modelos_3d/')),
            ],
        ),
    ]
