# Generated by Django 5.1.6 on 2025-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagem',
            field=models.ImageField(upload_to='cartas/modelos_carta/'),
        ),
    ]
