# Generated by Django 5.1.6 on 2025-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0002_alter_carta_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagem',
            field=models.ImageField(upload_to='modelos_carta/'),
        ),
    ]
