# Generated by Django 5.1.6 on 2025-02-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0003_alter_carta_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagem',
            field=models.ImageField(upload_to='media/modelos_carta/'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='modelo_3d',
            field=models.FileField(upload_to='media/modelos_3d/'),
        ),
    ]
