# Generated by Django 5.1.6 on 2025-02-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0004_alter_carta_imagem_alter_carta_modelo_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='marcador_nft_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
