# Generated by Django 5.1.6 on 2025-02-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0005_carta_marcador_nft_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='categoria',
            field=models.CharField(choices=[('astronomia', 'Astronomia'), ('ciencias', 'Ciências'), ('biologia', 'Biologia')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='imagem',
            field=models.ImageField(upload_to='media/modelos_carta/', verbose_name='Imagem da Carta'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='marcador_nft_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL do Marcador NFT'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='modelo_3d',
            field=models.FileField(upload_to='media/modelos_3d/', verbose_name='Modelo 3D'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
