# Generated by Django 5.1.6 on 2025-02-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0006_alter_carta_categoria_alter_carta_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='categoria',
            field=models.CharField(choices=[('astronomia', 'Astronomia'), ('ciencias', 'Ciências'), ('biologia', 'Biologia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carta',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carta',
            name='imagem',
            field=models.ImageField(upload_to='media/modelos_carta/'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='marcador_nft_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carta',
            name='modelo_3d',
            field=models.FileField(upload_to='media/modelos_3d/'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
