# Generated by Django 5.1.6 on 2025-02-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0007_alter_carta_categoria_alter_carta_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagem',
            field=models.ImageField(upload_to='modelos_carta/'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='modelo_3d',
            field=models.FileField(upload_to='modelos_3d/'),
        ),
    ]
