# Generated by Django 5.1.6 on 2025-02-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0008_alter_carta_imagem_alter_carta_modelo_3d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='marcador_nft_url',
        ),
        migrations.AddField(
            model_name='carta',
            name='marcador_nft',
            field=models.ImageField(blank=True, null=True, upload_to='marcadores/'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='categoria',
            field=models.CharField(choices=[('astronomia', 'Astronomia'), ('ciencias', 'Ciências'), ('biologia', 'Biologia'), ('outro', 'Outro')], default='Outro', max_length=20),
        ),
        migrations.AlterField(
            model_name='carta',
            name='imagem',
            field=models.ImageField(upload_to='cartas/'),
        ),
    ]
