# Generated by Django 5.1.6 on 2025-02-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0009_remove_carta_marcador_nft_url_carta_marcador_nft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='marcador_nft',
        ),
        migrations.AddField(
            model_name='carta',
            name='mind_target',
            field=models.FileField(blank=True, null=True, upload_to='mind-targets/'),
        ),
    ]
