# Generated by Django 5.1.6 on 2025-02-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0010_remove_carta_marcador_nft_carta_mind_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='mind_target',
            field=models.FileField(blank=True, null=True, upload_to='mind_targets/'),
        ),
    ]
